# Generated by Django 5.2.6 on 2025-10-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_fotocomprada_pedido_itempedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, help_text='Ex: 20.00 para 20% de desconto.', max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
