# Generated by Django 5.2.6 on 2025-10-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_cupom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
