# Generated by Django 5.2.6 on 2025-10-05 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_pedido_stripe_payment_intent_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='fotografo',
            field=models.ForeignKey(blank=True, limit_choices_to={'papel': 'FOTOGRAFO'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
