# Generated by Django 5.2.6 on 2025-10-05 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_cupom_fotografo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.cupom'),
        ),
    ]
