# Generated by Django 5.2.6 on 2025-10-19 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_carrinho_cupom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='fotografo',
            field=models.ForeignKey(default=3, limit_choices_to={'papel': 'FOTOGRAFO'}, on_delete=django.db.models.deletion.CASCADE, related_name='cupons', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
