# Generated by Django 5.2.6 on 2026-02-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_cupom_fotografo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='stripe_payment_intent_id',
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_pagamento_externo',
            field=models.CharField(blank=True, help_text='ID da transação no Mercado Pago', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(default='MERCADO_PAGO', max_length=50),
        ),
    ]
