# Generated by Django 5.2.6 on 2026-04-13 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_remove_pedido_stripe_payment_intent_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='pago_ao_fotografo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HistoricoPagamentoFotografo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia_inicio', models.DateField(blank=True, null=True)),
                ('referencia_fim', models.DateField(blank=True, null=True)),
                ('fotografo', models.ForeignKey(limit_choices_to={'papel': 'FOTOGRAFO'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
