# Generated by Django 5.2.6 on 2026-08-11 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0015_alter_video_titulo'),
        ('loja', '0009_itempedido_pago_ao_fotografo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_fotos', models.PositiveIntegerField(verbose_name='Quantidade de Fotos Desejadas')),
                ('valor_oferecido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Oferecido (R$)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente (Aguardando Resposta)'), ('ACEITA', 'Aceita pelo Fotógrafo'), ('RECUSADA', 'Recusada pelo Fotógrafo')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_recebidas', to='galeria.album')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_feitas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
