# Generated by Django 5.2.6 on 2026-08-11 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0015_alter_video_titulo'),
        ('loja', '0010_propostacompra'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fotocomprada',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galeria.video'),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galeria.video'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='galeria.video'),
        ),
        migrations.AlterField(
            model_name='fotocomprada',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galeria.foto'),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galeria.foto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='galeria.foto'),
        ),
    ]
