# Generated by Django 5.2.6 on 2026-08-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_alter_itemcarrinho_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostacompra',
            name='quantidade_videos',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de Vídeos'),
        ),
        migrations.AddField(
            model_name='propostacompra',
            name='valor_contraproposta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Contra-proposta (R$)'),
        ),
        migrations.AlterField(
            model_name='propostacompra',
            name='quantidade_fotos',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de Fotos'),
        ),
        migrations.AlterField(
            model_name='propostacompra',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente (Aguardando Fotógrafo)'), ('ACEITA', 'Aceita pelo Fotógrafo'), ('RECUSADA', 'Recusada pelo Fotógrafo'), ('CONTRAPROPOSTA', 'Contra-proposta Enviada'), ('CONTRAPROPOSTA_ACEITA', 'Contra-proposta Aceita pelo Cliente'), ('CONTRAPROPOSTA_RECUSADA', 'Contra-proposta Recusada pelo Cliente')], default='PENDENTE', max_length=30),
        ),
    ]
