# Generated by Django 5.2.6 on 2026-08-13 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_propostacompra_quantidade_videos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoSaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Solicitado (R$)')),
                ('chave_pix', models.CharField(help_text='Chave PIX para recebimento', max_length=255, verbose_name='Chave PIX')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente (Aguardando Pagamento)'), ('PAGO', 'Pago'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=20)),
                ('observacao', models.TextField(blank=True, help_text='Motivo em caso de recusa ou ID de transação bancária', null=True, verbose_name='Observação/Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fotografo', models.ForeignKey(limit_choices_to={'papel': 'FOTOGRAFO'}, on_delete=django.db.models.deletion.CASCADE, related_name='saques_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
