# Generated by Django 5.2.6 on 2026-08-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_solicitacaosaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaosaque',
            name='comprovante',
            field=models.FileField(blank=True, help_text='Comprovante de transferência (Imagem ou PDF)', null=True, upload_to='comprovantes_saque/'),
        ),
    ]
