# Generated by Django 5.2.6 on 2026-09-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0014_solicitacaosaque_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostacompra',
            name='comentario',
            field=models.TextField(blank=True, help_text='Mensagem opcional do cliente para o fotógrafo', null=True, verbose_name='Comentário do Cliente'),
        ),
    ]
