# render.yaml (VERSÃO FINAL E CORRETA)

services:
  # 1. O nosso Servidor Web (Django + Gunicorn)
  - type: web
    name: django-backend
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: redis-service
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.4 # Ajuste se a sua versão for diferente

  # 2. O nosso "Trabalhador" de Fundo (Celery Worker)
  - type: worker
    name: celery-worker
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A config worker -l info -P gevent"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: redis-service
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.4 # Ajuste se a sua versão for diferente
  
  # 3. A nossa Base de Dados PostgreSQL (declarada como um serviço privado 'pserv')
  - type: pserv
    name: postgres-db
    plan: free
    postgres:
      version: 14

  # 4. O nosso servidor Redis (declarado como um serviço 'redis')
  - type: redis
    name: redis-service
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0 # Esta é a sintaxe correta (source, não cidr)
        description: "Permitir todas as ligações"