# Generated by Django 5.2.6 on 2026-04-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_remove_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='papel',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('FOTOGRAFO', 'Fotógrafo'), ('ADMIN', 'Administrador'), ('JORNALISTA', 'Jornalista'), ('ASSESSOR_IMPRENSA', 'Assessor de Imprensa'), ('ASSESSOR_COMUNICACAO', 'Assessor de Comunicação'), ('VIDEOMAKER', 'Videomaker'), ('CRIADOR_CONTEUDO', 'Criador de Conteúdo')], default='CLIENTE', max_length=50),
        ),
    ]
