# Generated by Django 5.2.6 on 2026-04-23 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_usuario_papel'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornalParceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jornal', models.CharField(help_text='Ex: Jornal O Globo', max_length=150)),
                ('ftp_host', models.CharField(help_text='Ex: ftp.oglobo.com.br', max_length=200)),
                ('ftp_user', models.CharField(max_length=100)),
                ('ftp_password', models.CharField(max_length=100)),
                ('ftp_pasta', models.CharField(default='/', help_text='Pasta de destino (ex: /public_html/esportes)', max_length=100)),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para suspender o envio para este jornal temporariamente.')),
                ('usuario', models.OneToOneField(limit_choices_to={'papel__in': ['JORNALISTA', 'ASSESSOR_IMPRENSA']}, on_delete=django.db.models.deletion.CASCADE, related_name='ftp_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
