# Generated by Django 5.2.6 on 2026-04-23 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_alter_jornalparceiro_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalparceiro',
            name='usuario',
            field=models.ForeignKey(limit_choices_to={'papel': 'FOTOGRAFO'}, on_delete=django.db.models.deletion.CASCADE, related_name='ftp_config', to=settings.AUTH_USER_MODEL),
        ),
    ]
