# Generated by Django 5.2.6 on 2026-08-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_jornalparceiro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mostrar_no_quem_somos',
            field=models.BooleanField(default=True, help_text='Desmarque para esconder fotógrafos independentes da página oficial da equipe.', verbose_name='Mostrar no Quem Somos'),
        ),
    ]
