# Generated by Django 5.2.6 on 2026-08-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_usuario_mostrar_no_quem_somos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaImprensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Goleiro Jonathan Queiroz defende pênalti decisivo e garante vitória de seu time', max_length=255)),
                ('veiculo', models.CharField(help_text='Ex: Globo Esporte, Rádio Planalto', max_length=150)),
                ('link', models.URLField(max_length=500)),
                ('data_publicacao', models.DateField()),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
