# Generated by Django 5.2.6 on 2026-08-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_materiaimprensa'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaimprensa',
            name='imagem_capa',
            field=models.ImageField(blank=True, help_text='Faça o upload da imagem da matéria', null=True, upload_to='imprensa_capas/'),
        ),
        migrations.AlterField(
            model_name='materiaimprensa',
            name='titulo',
            field=models.CharField(help_text='Ex: Goleiro Jonathan Queiroz defende pênalti decisivo...', max_length=255),
        ),
    ]
