# Generated by Django 5.2.6 on 2025-10-14 15:18

import config.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_perfilfotografo_cep_perfilfotografo_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilfotografo',
            name='especialidade',
            field=models.CharField(blank=True, help_text='Ex: Fotógrafo Esportivo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilfotografo',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, storage=config.storages.PublicMediaStorage(), upload_to='fotografo_perfis/'),
        ),
        migrations.AddField(
            model_name='perfilfotografo',
            name='rede_social',
            field=models.CharField(blank=True, help_text='Ex: @seu_instagram', max_length=255, null=True),
        ),
    ]
