# Generated by Django 5.2.6 on 2025-09-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='miniatura_marca_dagua',
            field=models.ImageField(blank=True, null=True, upload_to='miniaturas/%Y/%m/%d/'),
        ),
    ]
