# Generated by Django 5.2.6 on 2025-09-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_foto_miniatura_marca_dagua'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
