# Generated by Django 5.2.6 on 2025-10-01 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_foto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='categoria',
            field=models.CharField(choices=[('ARTES_MARCIAIS', 'Artes Marciais'), ('AUTOMOBILISMO', 'Automobilismo'), ('FUTEBOL', 'Futebol'), ('FUTSAL', 'Futsal'), ('BASQUETE', 'Basquete'), ('ATLETISMO', 'Atletismo'), ('FUTEBOL_AMERICANO', 'Futebol Americano'), ('RUGBY', 'Rugby'), ('NATACAO', 'Natação'), ('VOLLEYBALL', 'Volleyball'), ('OUTRO', 'Outro')], default='OUTRO', max_length=50),
        ),
        migrations.AddField(
            model_name='album',
            name='is_publico',
            field=models.BooleanField(default=True, help_text='Se marcado, o álbum será visível para todos os visitantes.'),
        ),
        migrations.AddField(
            model_name='album',
            name='local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, help_text="Link personalizado. Ex: 'campeonato-futebol-2025'. Deixe em branco para gerar automaticamente.", max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('arquivo_video', models.FileField(upload_to='videos/%Y/%m/%d/')),
                ('miniatura', models.ImageField(help_text='Thumbnail de pré-visualização para o vídeo.', upload_to='videos_thumbnails/%Y/%m/%d/')),
                ('preco', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='galeria.album')),
            ],
        ),
    ]
