# Generated by Django 5.2.6 on 2025-10-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_album_categoria_album_is_publico_album_local_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceIndexada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rekognition_face_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('data_indexacao', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces_indexadas', to='galeria.foto')),
            ],
        ),
    ]
