# Generated by Django 5.2.6 on 2025-10-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_faceindexada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='miniatura',
            field=models.ImageField(blank=True, help_text='Thumbnail de pré-visualização para o vídeo.', null=True, upload_to='videos_thumbnails/%Y/%m/%d/'),
        ),
    ]
