# Generated by Django 5.2.6 on 2025-10-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_video_miniatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='capa',
            field=models.ImageField(blank=True, help_text='Imagem de capa do álbum.', null=True, upload_to='album_capas/'),
        ),
    ]
