# Generated by Django 5.2.6 on 2025-10-07 20:57

import config.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_album_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='capa',
            field=models.ImageField(blank=True, help_text='Imagem de capa do álbum.', null=True, storage=config.storages.PublicMediaStorage(), upload_to='album_capas/'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='imagem',
            field=models.ImageField(storage=config.storages.PrivateMediaStorage(), upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='miniatura_marca_dagua',
            field=models.ImageField(blank=True, null=True, storage=config.storages.PublicMediaStorage(), upload_to='miniaturas/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='arquivo_video',
            field=models.FileField(storage=config.storages.PrivateMediaStorage(), upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='miniatura',
            field=models.ImageField(blank=True, help_text='Thumbnail de pré-visualização para o vídeo.', null=True, storage=config.storages.PublicMediaStorage(), upload_to='videos_thumbnails/'),
        ),
    ]
