# Generated by Django 5.2.6 on 2025-10-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_alter_album_capa_alter_foto_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='rotacao',
            field=models.IntegerField(default=0),
        ),
    ]
