# Generated by Django 5.2.6 on 2025-10-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0009_foto_rotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, help_text='Link personalizado. Deixe em branco para gerar automaticamente.', max_length=255, unique=True),
        ),
    ]
