# Generated by Django 5.2.6 on 2025-11-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0010_alter_album_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_arquivado',
            field=models.BooleanField(default=False, help_text='Se marcado, o álbum não será visível no site público.'),
        ),
        migrations.AddField(
            model_name='foto',
            name='is_arquivado',
            field=models.BooleanField(default=False, help_text='Se marcado, a foto não será visível no site público.'),
        ),
    ]
