# Generated by Django 5.2.6 on 2026-03-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0011_album_is_arquivado_foto_is_arquivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='pct_desconto_1',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentagem do Desconto 1 (Ex: 5.00 para 5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='album',
            name='pct_desconto_2',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentagem do Desconto 2 (Ex: 10.00 para 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='album',
            name='pct_desconto_3',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentagem do Desconto 3 (Ex: 15.00 para 15%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='album',
            name='qtd_desconto_1',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de fotos para ativar o Desconto 1 (Ex: 5)'),
        ),
        migrations.AddField(
            model_name='album',
            name='qtd_desconto_2',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de fotos para ativar o Desconto 2 (Ex: 10)'),
        ),
        migrations.AddField(
            model_name='album',
            name='qtd_desconto_3',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de fotos para ativar o Desconto 3 (Ex: 15)'),
        ),
    ]
