# Generated by Django 5.2.6 on 2026-03-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0012_album_pct_desconto_1_album_pct_desconto_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local do Evento'),
        ),
    ]
