# Generated by Django 5.2.6 on 2026-07-21 00:50

import config.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0013_alter_album_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='arquivo_preview',
            field=models.FileField(blank=True, null=True, storage=config.storages.PublicMediaStorage(), upload_to='videos_previews/'),
        ),
    ]
