# Generated by Django 5.2.6 on 2026-07-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0014_video_arquivo_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
