# Generated by Django 5.2.6 on 2026-08-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0015_alter_video_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=150, verbose_name='Nome do Cliente')),
                ('papel', models.CharField(blank=True, max_length=150, null=True, verbose_name='Papel/Cargo (Ex: Atleta, Clube)')),
                ('texto', models.TextField(verbose_name='Avaliação/Depoimento')),
                ('estrelas', models.PositiveIntegerField(default=5, help_text='Número de estrelas de 1 a 5')),
                ('mostrar_na_home', models.BooleanField(default=True, verbose_name='Mostrar na Home Page')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
