# Generated by Django 5.2.6 on 2026-08-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0016_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='categoria',
            field=models.CharField(blank=True, help_text='Ex: Jogo 1, Premiação, Bastidores', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='categoria',
            field=models.CharField(blank=True, help_text='Ex: Jogo 1, Premiação, Bastidores', max_length=100, null=True),
        ),
    ]
